todo/urls.py
from django.urls import path
from .views import (
    index,
    add_task,
    tag_list,
    update_tag,
    delete_tag,
    add_tag,
    update_task,
    delete_task,
    toggle_task_status,
)

urlpatterns = [
    path("", index, name="index"),
    path("add_task/", add_task, name="add_task"),
    path("add_tag/", add_tag, name="add_tag"),
    path("tag/list/", tag_list, name="tag_list"),
    path("tag/update/<int:pk>/", update_tag, name="update_tag"),
    path("tag/delete/<int:pk>/", delete_tag, name="delete_tag"),
    path("task/update/<int:pk>/", update_task, name="update_task"),
    path("task/delete/<int:pk>/", delete_task, name="delete_task"),
    path("task/toggle/<int:pk>/", toggle_task_status, name="toggle_task_status"),
]

app_name = "todo"

todo_pr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("accounts/", include("django.contrib.auth.urls")),
]

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks", blank=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="tasks",
    )

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["is_done"]


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import Task, Tag
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["content", "deadline", "is_done", "owner","tags"]


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["content", "is_done", "deadline"]

    def __init__(self, *args, **kwargs):
        super(TaskUpdateForm, self).__init__(*args, **kwargs)
        self.fields["deadline"].help_text = (
            "Enter the deadline for the task (Format: YYYY-MM-DD HH:MM:SS)"
        )
        self.helper = FormHelper()
        self.helper.layout = Layout(
            "content",
            "is_done",
            "deadline",
            Submit("update", "Update Task", css_class="btn-primary"),
        )


class SearchForm(forms.Form):
    tag_search = forms.CharField(max_length=100, required=False)

todo/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import TaskForm, TagForm, TaskUpdateForm, SearchForm
from .models import Task, Tag


@login_required
def index(request: HttpRequest) -> HttpResponse:
    tag_search = request.GET.get("tag-search")
    tasks = Task.objects.all()

    if tag_search:
        tasks = tasks.filter(tags__name__icontains=tag_search)

    paginator = Paginator(tasks, 5)
    page = request.GET.get("page")

    try:
        tasks = paginator.page(page)
    except PageNotAnInteger:
        tasks = paginator.page(1)
    except EmptyPage:
        tasks = paginator.page(paginator.num_pages)

    context = {
        "tasks": tasks,
        "page_obj": tasks,
        "is_paginated": paginator.num_pages > 1,
    }

    return render(request, "todo/index.html", context)


def add_task(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todo:index")
    else:
        form = TaskForm()

    return render(request, "todo/add_task.html", {"form": form})


def add_tag(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("todo:tag_list")
    else:
        form = TagForm()

    return render(request, "todo/add_tag.html", {"form": form})


def tag_list(request: HttpRequest) -> HttpResponse:
    tags = Tag.objects.all()
    return render(request, "todo/tag_list.html", {"tags": tags})


def update_tag(request: HttpRequest, pk: int) -> HttpResponse:
    tag = Tag.objects.get(id=pk)

    if request.method == "POST":
        form = TagForm(request.POST, instance=tag)
        if form.is_valid():
            form.save()
            return redirect("todo:tag_list")
    else:
        form = TagForm(instance=tag)

    return render(request, "todo/update_tag.html", {"form": form, "tag": tag})


def delete_tag(request: HttpRequest, pk: int) -> HttpResponse:
    tag = Tag.objects.get(id=pk)
    tag.delete()
    return redirect("todo:tag_list")


def update_task(request: HttpRequest, pk: int) -> HttpResponse:
    task = Task.objects.get(id=pk)

    if request.method == "POST":
        form = TaskUpdateForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("todo:index")
    else:
        form = TaskUpdateForm(instance=task)

    return render(request, "todo/update_task.html", {"form": form})


def delete_task(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return redirect("todo:index")


def toggle_task_status(request: HttpRequest, pk: int) -> HttpResponse:
    task = Task.objects.get(id=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("todo:index")

templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>ToDo App</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2 mt-5">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">

      {% block content %}{% endblock %}
      {% block pagination %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=1 %}" class="page-link">First</a>
      </li>
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">Previous</a>
      </li>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
      {% if num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item {% if num == page_obj.number %}active{% endif %}">
          <a href="?{% query_transform request page=num %}" class="page-link">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">Next</a>
      </li>
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.paginator.num_pages %}" class="page-link">Last</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="list-group sidebar">
  {% if user.is_authenticated %}
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <p class="user-name btn btn-outline-info my-2 my-sm-0 mb-2" style="margin-right: 10px;">
         Welcome  @{{ user.username|capfirst }}
      </p>
      <p></p>
      <button type="submit" class="btn btn-outline-info my-2 my-sm-0">Log out</button>
    </form>
    {% else %}
      <div class="auth">
        <a href="{% url 'login' %}" class="login btn btn-outline-info my-2 my-sm-0 btn-lg" style="float: right;">Sign in</a>
      </div>
  {% endif %}
  <br>
  <li class="list-group-item"><a href="{% url 'todo:index' %}" class="list-group-item-action">Home page</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag_list' %}" class="list-group-item-action">Tags</a></li>
</ul>

templates/todo/add_tag.html
{% extends "_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>Add Tag</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Add</button>
    <a href="{% url 'todo:tag_list' %}" class="btn btn-primary ml-3">Cancel</a>
  </form>
{% endblock %}

templates/todo/add_task.html
{% extends "_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2 class="mt-3">Add Task</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Add</button>
    <a href="{% url 'todo:index' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/todo/index.html
{% extends '_base.html' %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4 text-center">Todo List</h1>
    <div class="d-flex justify-content-between align-items-center">
        <form method="GET" class="form-inline mb-3">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search by Tag" name="tag-search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        <a href="{% url 'todo:add_task' %}" class="btn btn-primary add" title="Add New Task To List">Add Task</a>
    </div>
    <ul class="list-group">
        {% for task in tasks %}
        <li class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
                <div class="task-item">
                    <h5 class="mb-1">{{ task.content }}</h5>
                    <small>Created: {{ task.created_at }}
                      {% if task.deadline %}
                          Deadline: {{ task.deadline }}
                      {% endif %}
                    </small>
                    <small class="ml-3">Status:
                        <span class="badge {% if task.is_done %}badge-success{% else %}badge-secondary{% endif %}">
                            {{ task.is_done|yesno:"Done,Not Done" }}
                        </span>
                    </small>
                    <ul class="list-inline mt-2">
                        {% for tag in task.tags.all %}
                            <li class="list-inline-item"><span class="badge badge-info">{{ tag.name }}</span></li>
                        {% endfor %}
                    </ul>
                </div>
                <div>
                    <a href="{% url 'todo:toggle_task_status' pk=task.id %}" class="btn btn-info" title="{% if task.is_done %}Undo{% else %}Mark as done{% endif %}">
                        {% if task.is_done %}Undo{% else %}Mark as done{% endif %}
                    </a>
                    <a href="{% url 'todo:update_task' pk=task.id %}" class="btn btn-secondary" title="Update Task">Update</a>
                    <a href="{% url 'todo:delete_task' pk=task.id %}" class="btn btn-danger" title="Delete Task">Delete</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block pagination %}
  {% include "includes/pagination.html" %}
{% endblock %}

templates/todo/tag_list.html
{% extends "_base.html" %}
{% block content %}
    <p class="mt-5"></p>
    <h1>Tags
      <a href="{% url 'todo:add_tag' %}" class="btn btn-primary add-tag" title="Add New Tag">add tag</a>
    </h1>
    <table class="table">
      <thead>
          <tr>
              <th >Name</th>
              <th>Update</th>
              <th>Delete</th>
          </tr>
      </thead>
      <tbody>
          {% for tag in tags %}
          <tr>
              <td>{{ tag.name }}</td>
              <td><a href="{% url 'todo:update_tag' pk=tag.id %}" class="btn btn-primary">Update</a></td>
              <td><a href="{% url 'todo:delete_tag' pk=tag.id %}" class="btn btn-danger">Delete</a></td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
{% endblock %}

templates/todo/update_tag.html
{% extends "_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Update Tag</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update Tag</button>
    </form>
</div>
{% endblock %}

templates/todo/update_task.html
{% extends "_base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container mt-5">
    <h2  class="text-center">Update Task</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Update Task</button>
    </form>
</div>
{% endblock %}